/** Declaration file generated by dts-gen */

export function bodyDateParser(strict: boolean = true): any;

export function dateParser(strict: boolean = true): any;

export function parse(object: any, strict: boolean = true): void;

export function queryDateParser(strict: boolean = true): any;

