/** Declaration file generated by dts-gen */

export function bodyDateParser(): any;
export function bodyDateParser(strict: boolean): any;

export function dateParser(): any;
export function dateParser(strict: boolean): any;

export function parse(object: any): void;
export function parse(object: any, strict: boolean): void;

export function queryDateParser(): any;
export function queryDateParser(strict: boolean): any;

